export enum IdAction {
  Manage = 'manage',
  Insert = 'insert',
  Read = 'read',
  Submit = 'submit',
  Update = 'update',
  Import = 'import',
  Delete = 'delete',
  Request = 'request',
}

export enum IdSubject {
  All = 'all',
  Users = 'users',
  Roles = 'roles',
  StoredFiles = 'stored_files',
  Categories = 'categories',
  Topics = 'topics',
  Courses = 'courses',
  Sections = 'sections',
  Lessons = 'lessons',
  Discussions = 'discussions',
  Assignments = 'assignments',
  TeachingRequests = 'teaching_requests',
  LearningRequest = 'learning_requests',
  CourseTeacher = 'course_teachers',
  CourseStudents = 'course_students',
  NotificationSubscriptions = 'notification_subscriptions',
  CoursePrices = 'course_prices',
  Wallets = 'wallets',
}
