version: '3.8'

services:
  postgres:
    container_name: academy-postgres
    image: postgres:14
    restart: always
    volumes:
      - academy_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - '${DB_PORT}:5432'
    networks:
      - academy-network

  redis:
    container_name: academy-redis
    image: redis:7-alpine
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:6379
    networks:
      - academy-network

networks:
  academy-network:

volumes:
  academy_postgres_data:
