version: '3.8'

services:
  postgres:
    container_name: academy-postgres
    image: postgres:14
    restart: always
    volumes:
      - academy_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - '${DB_PORT}:5432'
    networks:
      - academy-network

  redis:
    container_name: academy-redis
    image: redis:7-alpine
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:6379
    networks:
      - academy-network

  server:
    container_name: server
    # image: harbor.zinza.com.vn/d2/zinza-id/zinza-id/id-server:dev
    restart: always
    depends_on:
      - id-postgres
      - id-redis
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    networks:
      - academy-network
    command: 'sh /docker-entrypoint.sh'

  client:
    container_name: client
    restart: always
    depends_on:
      - id-server
    env_file:
      - .env
    # image: harbor.zinza.com.vn/d2/zinza-id/zinza-id/id-client:dev
    ports:
      - '80:${CLIENT_PORT}'
    networks:
      - academy-network
    command: 'sh /docker-entrypoint.sh'

networks:
  academy-network:

volumes:
  academy_postgres_data:
  academy_minio_data:
