version: '3.8'

services:
  postgres:
    container_name: project-postgres
    image: postgres:14
    restart: always
    volumes:
      - project_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - '${DB_PORT}:5432'
    networks:
      - project-network

  minio:
    container_name: project-minio
    image: quay.io/minio/minio
    restart: always
    volumes:
      - project_minio_data:/data
    ports:
      - '${MINIO_API_PORT}:9000'
      - '${MINIO_CONSOLE_PORT}:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: 'server /data --console-address ":9001"'

networks:
  project-network:

volumes:
  project_postgres_data:
  project_minio_data:
