export enum AppSwaggerTag {
  App = 'app',
  Users = 'users',
  AuthGoogle = 'authGoogle',
  Auth = 'auth',
  Categories = 'categories',
  Topics = 'topics',
  Courses = 'courses',
  Sections = 'sections',
  Lessons = 'lessons',
  Discussions = 'discussions',
  Assignments = 'assignments',
  TeachingRequests = 'teaching-requests',
  LearningRequests = 'learining-requests',
}
