export enum QueryKeys {
  me = 'me',
  profile = 'profile',
  topics = 'topics',
  topic = 'topic',
  courses = 'courses',
  course = 'course',
  categories = 'categories',
  category = 'cateogry',
  assignments = 'assignments',
  discussions = 'discussions',
  teachingRequests = 'teachingRequests',
  learningRequests = 'learningRequests',
  users = 'users',
  userPublics = 'userPublics',
  courseLearnings = 'courseLearnings',
}
